# Generated by Django 5.0.2 on 2024-03-07 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='collection',
        ),
        migrations.AddField(
            model_name='category',
            name='collection',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='myapp.collection'),
            preserve_default=False,
        ),
    ]
